"""The pre-commit hooks must not fight the repository's own generators.

Two incidents this guards, both found by running `pre-commit run --all-files`
for the first time:

* `ruff-format`'s hook definition has declared `types_or: [python, pyi, jupyter,
  markdown]` since ruff-pre-commit v0.14, so it reformats Python fences *inside
  Markdown*. On this repo that rewrote `docs/COOKBOOK.md`'s mkdocs snippet
  directive `--8<-- "snippets/find-untagged.py"` into `--8 < --"..."`, which
  silently dropped the whole example from the published page — and
  `mkdocs build --strict` still exited 0, so neither the local gate nor the
  `lint` job noticed.
* `end-of-file-fixer` stripped the trailing blank line from
  `tests/fixtures/thread.mbox`, which `tests/fixtures/generate.py` writes back
  on the next run (1058 bytes → 1057 → 1058). Fixtures are generated, never
  hand-edited (CLAUDE.md), so a whitespace hook can only ever lose that fight.
"""

from __future__ import annotations

from pathlib import Path

import yaml

CONFIG = Path(__file__).resolve().parents[1] / ".pre-commit-config.yaml"

#: Hooks that rewrite the files they are given. Each must skip generated trees.
MUTATING = {"end-of-file-fixer", "trailing-whitespace", "ruff-check", "ruff-format"}

#: Generated byte-for-byte by tests/fixtures/generate.py.
GENERATED = "tests/fixtures/"


def _hooks() -> dict[str, dict]:
    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    return {hook["id"]: hook for repo in config["repos"] for hook in repo["hooks"]}


def test_the_config_is_loadable_and_states_the_hooks_we_think_it_does():
    """Guard the guard: the assertions below are vacuous if the ids move."""
    hooks = _hooks()
    missing = sorted(MUTATING - set(hooks))
    assert not missing, f".pre-commit-config.yaml no longer defines: {missing}"


def test_the_ruff_hooks_are_python_only():
    """`ruff format` on Markdown rewrites docs; see the module docstring."""
    for hook_id in ("ruff-check", "ruff-format"):
        types = _hooks()[hook_id].get("types_or")
        assert types is not None, (
            f"{hook_id} must pin `types_or` — ruff-pre-commit's default includes "
            "`markdown`, and formatting docs mangles mkdocs snippet directives"
        )
        assert "markdown" not in types, f"{hook_id} would reformat Markdown: {types}"


def test_the_whitespace_hooks_skip_generated_fixtures():
    hooks = _hooks()
    for hook_id in ("end-of-file-fixer", "trailing-whitespace"):
        exclude = hooks[hook_id].get("exclude", "")
        assert GENERATED in exclude, (
            f"{hook_id} must exclude {GENERATED} — the generator rewrites it back"
        )


def test_check_yaml_can_read_mkdocs_yml():
    """mkdocs-material's `!relative` tag has no safe-load constructor."""
    assert "--unsafe" in _hooks()["check-yaml"].get("args", []), (
        "check-yaml fails on mkdocs.yml's `!relative` tag without --unsafe"
    )
